name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: |
          npx playwright install
          npx playwright install-deps

#      - name: Verify Playwright Installation
#        run: npx playwright show-config

      - name: Run Playwright Tests
        run: npx playwright test
